-- inserts descuentos_academicos.tipo_duracion
INSERT INTO descuentos_academicos.tipo_duracion(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (1,'Anual',Anual,ANUAL, true,1, now(), now());
INSERT INTO descuentos_academicos.tipo_duracion(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (2,'Bimestral',Bimestral,BIMESTRAL, true,2, now(), now());
INSERT INTO descuentos_academicos.tipo_duracion(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (3,'Cuatrimestral',Cuatrimestral,CUATRIMENSTRAL, true,3, now(), now());
INSERT INTO descuentos_academicos.tipo_duracion(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (4,'Mensual',Mensual,MENSUAL, true,4, now(), now());
INSERT INTO descuentos_academicos.tipo_duracion(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (5,'Periodos',Periodos,PERIODOS, true,5, now(), now());
INSERT INTO descuentos_academicos.tipo_duracion(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (6,'Por cohorte',Por cohorte,POR COHORTE, true,6, now(), now());
INSERT INTO descuentos_academicos.tipo_duracion(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (7,'Semestral',Semestral,SEMESTRAL, true,7, now(), now());
INSERT INTO descuentos_academicos.tipo_duracion(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (8,'Sin definir',Sin definir,SIN DEFINIR, true,8, now(), now());
INSERT INTO descuentos_academicos.tipo_duracion(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (9,'Trimestral',Trimestral,TRIMESTRAL, true,9, now(), now());

-- inserts descuentos_academicos.tipo_descuento
INSERT INTO descuentos_academicos.tipo_descuento(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (1,'Certificación electoral',Certificaciones electorales 10%,CE, true,1, now(), now());
INSERT INTO descuentos_academicos.tipo_descuento(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (2,'Monitoría y/o asitencia académica',Monitores y/o asistentes académicos 50%,MONITORIA, true,2, now(), now());
INSERT INTO descuentos_academicos.tipo_descuento(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (3,'Representante de consejo superior y/o académico',Representante de consejo superior y/o académico 50%,RCSA, true,3, now(), now());
INSERT INTO descuentos_academicos.tipo_descuento(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (4,'Mejor saber- pro (ECAES)',Mejor saber- pro (ECAES) 100%,ECAES, true,4, now(), now());
INSERT INTO descuentos_academicos.tipo_descuento(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (5,'Pariente de personal de planta UD',Pariente de personal de planta UD 100%,PPUD, true,5, now(), now());
INSERT INTO descuentos_academicos.tipo_descuento(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (6,'Egresado UD',Egresado UD 30%,EGRESADO, true,6, now(), now());
INSERT INTO descuentos_academicos.tipo_descuento(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion,fecha_modificacion) VALUES (7,'Beca de secretaría de educación',Beca de secretaría de educación,BSEDU, true,7, now(), now());